# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8ea523fc1f8f0474fa515a66714fed38fe5bb2127cb9ddd1e0256f8965b6dfe9bbfac5133e11c3111d21acddcb1f9546ce5d84b0a8760cc130c17fee006b76d

test:
  secret_key_base: 02006a0b48fd12f84436615c7e8db0cbc34c30ae8bfff43717dd272e114af14507168303eeb1127caaf75bbecf0366b3726ac28f7e142b7e625ea402f6d530ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
