version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/rails-docker-test-1/blog
    steps:
      - checkout
          path: ~/rails-docker-test-1
      - ruby/install-deps
  
  test:
    docker:
      
workflows:
  version: 2
    